name: Update music files

# expected secrets: 
# =================
# secrets.CB_RELEASE_PAT
# secrets.FTP_PASSWORD
#
# expected variables:
# ===================
# vars.FTP_HOST 
# vars.FTP_USER 
# vars.FTP_TARGETDIR 

on:
  push:
    branches: [ main ]

jobs:
  build_midi:
    runs-on: windows-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # this is to get "git diff" to print filenames with unicode characters better
    - name: Configure repo
      run: git config --local core.quotePath false

    - name: download tools
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'jonashogstrom/ChoirBuddyTools'
        version: 'tags/r0.1.1.49_3'
        file: 'nwc2mid_release.zip'
        target: 'temp/dl/nwc2mid.zip'
        token: ${{ secrets.CB_RELEASE_PAT }}
    
    - name: Extract tools
      run: 7z x temp/dl/nwc2mid.zip -otemp/tools/
  
    - name: Generate midi files
      run: temp/tools/nwc2mid.exe

    - name: Upload midi files 
      uses: actions/upload-artifact@v3
      with:
        name: midifiles_${{steps.version.outputs.version}}
        path: stage/**/*.*

    - name: Cache generated midi files
      uses: actions/cache/save@v3
      with:
        enableCrossOsArchive: true
        path: stage
        key: midi-cache-${{ github.sha }}

  build_mp3:
    needs: build_midi
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Restore cached midi files
      uses: actions/cache/restore@v3
      with:
        path: stage
        key: midi-cache-${{ github.sha }}
        
    - name: download tools
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'jonashogstrom/ChoirBuddyTools'
        version: 'tags/r0.1.1.49_3'
        file: 'mid2mp3.zip'
        target: '${{runner.temp}}/dl/mid2mp3.zip'
        token: ${{ secrets.CB_RELEASE_PAT }}

    - name: Extract tools
      run: 7z x ${{runner.temp}}/dl/mid2mp3.zip -o${{runner.temp}}/tools

    - name: Fix executable flag
      run: chmod 755 ${{runner.temp}}/tools/*.sh

    - name: Update apt
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt-get install -y timidity ffmpeg

    - name: Generate mp3-files
      run: find ${{github.workspace}}/stage -name "*.mid" -type f -print0 | xargs --no-run-if-empty -0 -L 1 bash ${{runner.temp}}/tools/mid2mp3.sh

    - name: Upload all files to server
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ vars.FTP_HOST }}
        ftp_username: ${{ vars.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "stage"
        dist_target_dir: ${{ vars.FTP_TARGETDIR }}
        delete: "false"

    - name: Update the watermark tag
      uses: richardsimko/update-tag@v1
      with:
        tag_name: Converted
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
